###############################################################################
# Created by write_sdc
###############################################################################
current_design cpu_core
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 25.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cs}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_ack}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[10]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[11]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[12]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[13]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[14]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[15]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[16]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[17]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[18]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[19]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[20]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[21]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[22]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[23]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[24]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[25]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[26]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[27]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[28]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[29]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[30]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[31]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[5]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[6]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[7]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[8]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_slave_data[9]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cpu_halted}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[0]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[10]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[11]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[12]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[13]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[14]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[15]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[16]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[17]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[18]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[19]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[1]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[20]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[21]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[22]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[23]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[24]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[25]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[26]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[27]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[28]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[29]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[2]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[30]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[31]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[32]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[33]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[34]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[35]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[36]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[37]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[38]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[39]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[3]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[40]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[41]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[42]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[43]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[44]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[45]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[46]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[47]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[48]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[4]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[5]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[6]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[7]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[8]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_data[9]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ram_master_req}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {cpu_halted}]
set_load -pin_load 0.0334 [get_ports {ram_master_req}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[48]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[47]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[46]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[45]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[44]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[43]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[42]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[41]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[40]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[39]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[38]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[37]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[36]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[35]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[34]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[33]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[32]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[31]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[30]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[29]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[28]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[27]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[26]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[25]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[24]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[23]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[22]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[21]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[20]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[19]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[18]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[17]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[16]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[15]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[14]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[13]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[12]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[11]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[10]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[9]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[8]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[7]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[6]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[5]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[4]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[3]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[2]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[1]}]
set_load -pin_load 0.0334 [get_ports {ram_master_data[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cs}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_ack}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ram_slave_data[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
