// Auto-generated by OpenLane
module alu(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input cs,
  input[31:0] a,
  input[31:0] b,
  input[3:0] op,
  output ready,
  output[31:0] result1,
  output[31:0] result2
);
endmodule
