###############################################################################
# Created by write_sdc
###############################################################################
current_design register_file
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 25.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_1[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_1[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_1[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_1[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_1[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_2[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_2[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_2[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_2[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_2[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_3[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_3[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_3[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_3[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_addr_3[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_addr[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_addr[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_addr[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_addr[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_addr[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[10]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[11]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[12]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[13]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[14]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[15]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[16]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[17]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[18]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[19]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[20]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[21]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[22]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[23]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[24]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[25]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[26]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[27]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[28]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[29]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[30]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[31]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[5]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[6]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[7]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[8]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[9]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_en}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[0]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[10]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[11]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[12]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[13]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[14]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[15]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[16]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[17]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[18]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[19]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[1]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[20]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[21]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[22]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[23]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[24]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[25]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[26]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[27]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[28]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[29]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[2]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[30]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[31]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[3]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[4]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[5]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[6]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[7]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[8]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_1[9]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[0]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[10]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[11]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[12]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[13]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[14]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[15]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[16]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[17]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[18]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[19]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[1]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[20]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[21]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[22]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[23]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[24]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[25]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[26]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[27]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[28]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[29]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[2]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[30]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[31]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[3]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[4]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[5]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[6]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[7]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[8]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_2[9]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[0]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[10]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[11]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[12]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[13]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[14]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[15]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[16]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[17]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[18]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[19]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[1]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[20]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[21]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[22]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[23]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[24]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[25]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[26]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[27]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[28]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[29]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[2]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[30]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[31]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[3]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[4]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[5]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[6]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[7]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[8]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data_3[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {read_data_1[31]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[30]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[29]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[28]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[27]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[26]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[25]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[24]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[23]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[22]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[21]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[20]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[19]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[18]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[17]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[16]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[15]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[14]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[13]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[12]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[11]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[10]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[9]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[8]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[7]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[6]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[5]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[4]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[3]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[2]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[1]}]
set_load -pin_load 0.0334 [get_ports {read_data_1[0]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[31]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[30]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[29]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[28]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[27]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[26]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[25]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[24]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[23]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[22]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[21]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[20]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[19]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[18]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[17]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[16]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[15]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[14]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[13]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[12]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[11]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[10]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[9]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[8]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[7]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[6]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[5]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[4]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[3]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[2]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[1]}]
set_load -pin_load 0.0334 [get_ports {read_data_2[0]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[31]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[30]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[29]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[28]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[27]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[26]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[25]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[24]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[23]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[22]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[21]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[20]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[19]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[18]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[17]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[16]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[15]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[14]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[13]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[12]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[11]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[10]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[9]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[8]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[7]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[6]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[5]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[4]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[3]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[2]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[1]}]
set_load -pin_load 0.0334 [get_ports {read_data_3[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_en}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_1[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_1[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_1[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_1[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_1[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_2[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_2[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_2[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_2[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_2[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_3[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_3[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_3[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_3[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_addr_3[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_addr[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_addr[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_addr[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_addr[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_addr[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {write_data[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
