// Auto-generated by OpenLane
module cpu_core(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input cs,
  input ram_slave_ack,
  input[31:0] ram_slave_data,
  output ram_master_req,
  output[48:0] ram_master_data,
  output cpu_halted
);
endmodule
