// Auto-generated by OpenLane
module register_file(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input[4:0] read_addr_1,
  output[31:0] read_data_1,
  input[4:0] read_addr_2,
  output[31:0] read_data_2,
  input[4:0] read_addr_3,
  output[31:0] read_data_3,
  input write_en,
  input[4:0] write_addr,
  input[31:0] write_data
);
endmodule
